# Generated by Django 5.1.2 on 2024-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dish_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
    ]
