# Generated by Django 4.2.16 on 2024-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dish_category_dish_image_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_profiles/'),
        ),
    ]
