# Generated by Django 4.2.16 on 2024-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Order Received', 'Order Received'), ('Preparing', 'Preparing'), ('On the Way', 'On the Way'), ('Pick up Ready', 'Pick up Ready'), ('Delivered', 'Delivered'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
    ]
