# Generated by Django 4.2.16 on 2024-10-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_items_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], default='delivery', max_length=20),
        ),
    ]
